clock.h
SYSCTL_RCGC2_R
SYSCTL_RIS_R
SYSCTL_RCC_R
SYSCTL_RCC2_R
NVIC_ST_CTRL_R
NVIC_ST_RELOAD_R
NVIC_ST_CURRENT_R
void SysTickInit()
Initializes sys tick.
References NVIC_ST_CTRL_R, NVIC_ST_CURRENT_R, NVIC_ST_RELOAD_R.
Referenced by ClockInit.
void PLLInit()
Initalizes the PLL to 80 MHz.
References SYSCTL_RCC2_R, SYSCTL_RCC_R, SYSCTL_RIS_R.
Referenced by ClockInit.
void ClockInit()
Initializes the clock.
References PLLInit, SysTickInit.
Referenced by InitAll.
void SysTickWait(unsigned long delay)
Uses the 80 MHz PLL to create a delay in units of 12.5ns.
delay delay in units of 12.5ns
References NVIC_ST_CTRL_R, NVIC_ST_CURRENT_R, NVIC_ST_RELOAD_R.
Referenced by DelayMicro, DelayMilli, DelayNano.
void DelayNano(unsigned long nanoseconds)
Uses.
SysTickWait() to create a delay in units of nanoseconds nanoseconds delay of nanoseconds
References SysTickWait.
Referenced by LcdSendNibble.
void DelayMicro(unsigned long microseconds)
Uses.
DelayNano() to create a delay in units of microseconds microseconds delay of microseconds
References SysTickWait.
Referenced by KeypadWaitForChar, LcdCursorShift, LcdDisplayControl, LcdEntryModeSet, LcdFunctionSet, LcdInit, LcdPrintChar, LcdReturnHome, LcdSetDdram.
void DelayMilli(unsigned long milliseconds)
Uses.
DelayMicro() to create a delay in units of milliseconds millisecond delay of milliseconds
References SysTickWait.
Referenced by AfterEach, LcdClearDisplay, LcdInit, RunChangePassword, RunLogin, RunLoginAnimation, RunMain, TestKeypadLcd, TestLcdClear, TestLcdMultiLine.