flash.h
FLASH_STORAGE_H
FLASH_BOOTCFG_R
FLASH_FMA_R
FLASH_FMD_R
FLASH_FMC_R
FLASH_BASE_ADDR
FLASH_KB
FLASH_BLOCK_SIZE
FLASH_NUMBER_BLOCKS
void FlashInit()
Initializes flash storage.
References FLASH_BOOTCFG_R, flashWriteKey.
Referenced by InitAll.
int FlashWrite(FlashData data)
Writes data to flash.
data int
References FLASH_BASE_ADDR, FLASH_BLOCK_SIZE, FLASH_FMA_R, FLASH_FMC_R, FLASH_FMD_R, FlashErase, flashWriteKey.
Referenced by InitAll, RunChangePassword, TestFlash.
FlashData FlashRead()
Reads data from flash.
FlashData
References FLASH_BASE_ADDR, FLASH_BLOCK_SIZE, FlashData::passwordLength.
Referenced by InitAll, TestFlash.
int FlashErase()
Erases flash.
int
References FLASH_BASE_ADDR, FLASH_FMA_R, FLASH_FMC_R, FLASH_KB, FLASH_NUMBER_BLOCKS, flashWriteKey.
Referenced by FlashWrite, TestFlash.
bool FlashDataIsRead(FlashData data)
Checks if flash data is read.
data true false
References FlashData::password, FlashData::passwordLength.
Referenced by InitAll.