keypad.h
KEYPAD_H
KEYPAD_COL_PIN
KEYPAD_ROW_PIN
KEYPAD_N
SHIFT_CHAR
KEYPAD_UNKOWN_KEY
KEYPAD_MAX_SPECIAL_KEYS
SpecialKeyFunctions
KeyDisplayType
const KeyInfo KEYPAD_SPECIAL_KEYS[KEYPAD_MAX_SPECIAL_KEYS][KEYPAD_MAX_SPECIAL_KEYS]
Referenced by KeypadFindSpecialKey.
const char KEYPAD_KEYS[KEYPAD_N][KEYPAD_N][KEYPAD_N][KEYPAD_N]
Referenced by KeypadWaitForChar.
KeyInfo KeypadCreateDefaulteKey(char key)
Creates a default key with default values.
key KeyInfo
References DISPLAY_NORMAL, KeyInfo::isSpecial, NORMAL_NUMBER.
Referenced by KeypadWaitForKeyInfo, RunMain.
void KeypadInit()
Initializes the keypad.
References PortDInit, PortEInit.
Referenced by InitAll.
KeyInfo KeypadFindSpecialKey(char key)
Finds the KeyInfo of a given key.
key KeyInfo
References KeyInfo::key, KEYPAD_MAX_SPECIAL_KEYS, KEYPAD_SPECIAL_KEYS, KEYPAD_UNKOWN_KEY.
Referenced by KeypadWaitForKeyInfo.
bool KeyIsValid(KeyInfo key)
Checks if a given key is valid.
key true false
References KeyInfo::key, KEYPAD_UNKOWN_KEY.
Referenced by KeypadWaitForKeyInfo.
char KeypadWaitForChar()
Gets the character from the keypad.
char
References DelayMicro, KEYPAD_COL_PIN, KEYPAD_KEYS, KEYPAD_ROW_PIN.
Referenced by KeypadWaitForKeyInfo.
KeyInfo KeypadWaitForKeyInfo()
Waits for a key to be pressed.
KeyInfo
References KeyIsValid, KeypadCreateDefaulteKey, KeypadFindSpecialKey, KeypadWaitForChar.
Referenced by RunMain, TestKeypadLcd.