lcd.c
int currentRow
Referenced by LcdClearDisplay, LcdClearLastChar, LcdIncrementCursorRow, LcdPrintCharAt, LcdSetCursor.
int currentCol
Referenced by LcdClearDisplay, LcdClearLastChar, LcdIncrementCursorCol, LcdIncrementCursorRow, LcdPrintCharAt, LcdSetCursor.
void LcdIncrementCursorRow()
Increments the cursor row.
References currentCol, currentRow, LCD_N_ROW, LcdSetCursor.
Referenced by LcdIncrementCursorCol, LcdPrintChar.
void LcdIncrementCursorCol()
Increments the cursor column.
References currentCol, LCD_N_COL, LcdIncrementCursorRow.
Referenced by LcdPrintChar.
void LcdSetRs(byte rs)
Sets the rs flag to the given value.
rs rs == 1 -> data RS = HIGH, rs == 0 -> command RS = LOW
References LCD_RS.
Referenced by LcdClearDisplay, LcdCursorShift, LcdDisplayControl, LcdEntryModeSet, LcdFunctionSet, LcdInit, LcdPrintChar, LcdReturnHome, LcdSetDdram.
void LcdSendNibble(byte nibble)
Sends a nibble to the LCD.
nibble RS | R/W | DB4 | DB5 | DB6 | DB7
References DelayNano, HIGH, LCD_DB, LCD_EN, LOW.
Referenced by LcdInit, LcdSendByte.
void LcdSendByte(byte byte)
Sends a byte to the LCD.
byte the byte to be sent
References LcdSendNibble.
Referenced by LcdClearDisplay, LcdCursorShift, LcdDisplayControl, LcdEntryModeSet, LcdFunctionSet, LcdPrintChar, LcdReturnHome, LcdSetDdram.
void LcdClearDisplay()
Clears the display.
References currentCol, currentRow, DelayMilli, LcdSendByte, LcdSetRs, LOW.
Referenced by AfterEach, LcdInit, RefreshDisplay, RunChangePassword, RunLogin, RunLoginAnimation, RunMain, TestKeypadLcd, TestLcdClear, TestLcdMultiLine.
void LcdCursorShift(byte sc, byte rl)
Sets the LCD cursor position.
sc Display shift sc = 1, Cursor move sc = 0 rl Right shift rl = 1, Left shift rl = 0
References DelayMicro, HIGH, LcdSendByte, LcdSetRs.
void LcdEntryModeSet(byte id, byte s)
Sets the entry mode of the LCD.
id I / D = 1: Increment, I / D = 0: Decrement. s S = 1: The display shift, S = 0: The display does not shift.
References DelayMicro, LcdSendByte, LcdSetRs, LOW.
Referenced by LcdInit.
void LcdDisplayControl(byte d, byte c, byte b)
Controls the display, cursor, and blinking.
d D = 1: Display on, D = 0: Display off c C = 1: Cursor on, C = 0: Cursor off b B = 1: Blinks on, B= 0: Blinks off
References DelayMicro, LcdSendByte, LcdSetRs, LOW.
Referenced by LcdInit.
void LcdReturnHome()
Resets cursor to original position.
References DelayMicro, LcdSendByte, LcdSetRs, LOW.
void LcdFunctionSet(byte dl, byte n, byte f)
dl DL = 1: 8-bit length (DB7 - 0). DL = 0: 4-bit length (DB7 - 4). n N = 0: One-line display. N = 1: Two-line display f F = 0: 5 x 8 dots character font. F = 1: 5 x 10 dots character font.
References DelayMicro, LcdSendByte, LcdSetRs, LOW.
Referenced by LcdInit.
void LcdInit()
Initializes the LCD.
References DelayMicro, DelayMilli, LcdClearDisplay, LcdDisplayControl, LcdEntryModeSet, LcdFunctionSet, LcdSendNibble, LcdSetRs, LOW, PortAInit, PortBInit.
Referenced by InitAll.
void LcdSetDdram(byte addr)
Sets the DDRAM address (cursor position)
addr 7-bit address to be set
References DelayMicro, LcdSendByte, LcdSetRs, LOW.
Referenced by LcdSetCursor.
void LcdSetCursor(byte row, byte col, bool cursorTrack)
Sets the cursor position.
row row to be set col column to be set cursorTrack 1 -> Track cursor, 0 -> don't Track cursor
References currentCol, currentRow, LcdSetDdram.
Referenced by ClearAllInput, LcdClearLastChar, LcdClearRow, LcdIncrementCursorRow, LcdPrintCharAt, PrintData, RunLoginAnimation, TestLcdCursor, UpdateRows.
void LcdPrintChar(char ch, bool cursorTrack)
Prints a character to the LCD.
ch character to be printed cursorTrack 1 -> Track cursor, 0 -> don't Track cursor
References DelayMicro, HIGH, LcdIncrementCursorCol, LcdIncrementCursorRow, LcdSendByte, LcdSetRs.
Referenced by LcdClearRow, LcdPrintCharAt, LcdPrintString, PrintData, RunLoginAnimation, RunUserInput, TestKeypadLcd, TestLcdClear.
void LcdPrintCharAt(char ch, byte row, byte col)
Prints a character to the LCD at a given position.
ch character to be printed row row to be printed at col column to be printed at
References currentCol, currentRow, LcdPrintChar, LcdSetCursor.
Referenced by LcdClearLastChar, UpdateShift.
void LcdPrintString(char str[], bool cursorTrack)
Prints a string to the LCD.
str string to be printed
References LcdPrintChar.
Referenced by DisplayMessage, RunCalculator, RunChangePassword, RunLogin, RunLoginAnimation, TestFlash, TestKeypadLcd, TestLcdCursor, TestLcdMultiLine, UpdateRows.
void LcdClearRow(byte row)
Clears a row.
row
References LCD_N_COL, LcdPrintChar, LcdSetCursor.
Referenced by ClearAllInput.
void LcdClearLastChar(int rowLimit)
Clears the last character of a row.
rowLimit wont go to that row when clearing the last character
References currentCol, currentRow, LCD_N_COL, LcdPrintCharAt, LcdSetCursor.
Referenced by ClearLastInput.
void LcdClearCol(byte col)
References LCD_N_COL.