logic.c
bool isShiftOn
Referenced by GetSpecialFunction, RunMain, RunUserInput, UpdateShift.
bool isLoggedIn
bool isInit
Referenced by InitAll.
ProgramMode mode
Referenced by ClearAllInput, IsCalculatorAvailable, IsPasswordInputAvailable, RunChangePassword, RunLogin, RunMain, RunUserInput, UpdateRows.
TokenList tokenData
Referenced by ClearAllInput, ClearLastInput, InitAll, IsCalculatorAvailable, RunCalculator, RunUserInput, ShowCurrentData.
charList inputData
Referenced by ClearAllInput, ClearLastInput, InitAll, IsPasswordInputAvailable, RunChangePassword, RunLogin, RunUserInput, ShowCurrentData.
FlashData flashData
Referenced by InitAll, PasswordMatch, RunChangePassword.
void RunLogin()
References CALCULATOR_MODE, ClearAllInput, DelayMilli, inputData, LcdClearDisplay, LcdPrintString, mode, PasswordMatch, RunLoginAnimation, ShowCurrentData, UpdateRows.
Referenced by RunMain.
void RunChangePassword()
References CALCULATOR_MODE, DelayMilli, flashData, FlashWrite, inputData, LcdClearDisplay, LcdPrintString, mode, FlashData::password, FlashData::passwordLength, ShowCurrentData, UpdateRows.
Referenced by RunMain.
void RunCalculator()
References ClearAllInput, ParserInfo::currentResult, ParserInfo::error, INVALID_MATH_EXPRESSION, LCD_N_COL, LcdPrintString, MISSING_BRACKET, MISSING_NUMBER, MULTIPLE_DECIMAL_POINT, NO_ERROR, ParserCompile, ParserEndInput, ParserPushToken, ParserReset, SYNTAX_ERROR, tokenData.
Referenced by RunMain.
void RunLoginAnimation()
References DelayMilli, LcdClearDisplay, LcdPrintChar, LcdPrintString, LcdSetCursor, RandomRange.
Referenced by RunLogin.
Token GetKeyToken(KeyInfo key)
void ClearAllInput(bool clearData)
References CALCULATOR_MODE, inputData, LcdClearRow, LcdSetCursor, mode, tokenData.
Referenced by RunCalculator, RunLogin, RunMain.
void ClearLastInput()
References inputData, IsCalculatorAvailable, IsPasswordInputAvailable, LcdClearLastChar, tokenData.
Referenced by RunMain.
void ShowCurrentData()
References inputData, IsCalculatorAvailable, IsPasswordInputAvailable, PrintData, tokenData.
Referenced by RefreshDisplay, RunChangePassword, RunLogin.
void PrintData(void *data, int length, bool isToken)
References LcdPrintChar, LcdSetCursor, Token::value.
Referenced by ShowCurrentData.
bool IsCalculatorAvailable()
References CALCULATOR_MODE, mode, tokenData.
Referenced by ClearLastInput, ShowCurrentData.
bool IsPasswordInputAvailable()
References CHANGE_PASSWORD, inputData, LOGIN_MODE, mode.
Referenced by ClearLastInput, ShowCurrentData.
SpecialKeyFunctions GetSpecialFunction(KeyInfo key)
References isShiftOn, KeyInfo::normalFunction, KeyInfo::shiftFunction.
Referenced by RunMain, RunUserInput.
void MapFunctions(SpecialKeyFunctions function)
void ShowNumberOperation(KeyInfo key)
void UpdateShift()
References isShiftOn, LCD_CHAR_S, LCD_N_COL, LcdPrintCharAt, LOGIC_STATBAR_ROW.
Referenced by RunMain, UpdateRows.
bool PasswordMatch(charList password)
References flashData, FlashData::password, FlashData::passwordLength.
Referenced by RunLogin.
void DisplayMessage(char message[])
References LcdPrintString, UpdateRows.
void RefreshDisplay()
References LcdClearDisplay, ShowCurrentData, UpdateRows.
Referenced by RunMain.
void RunUserInput(KeyInfo key)
References CALCULATOR_MODE, DECIMAL, DECIMAL_POINT, GetSpecialFunction, inputData, isShiftOn, LcdPrintChar, mode, NORMAL_NUMBER, KeyInfo::normalDisplay, NUMBER, OPERATION, OPERATOR, PAST_ANSWER, PREVIOUS_ANSWER, KeyInfo::shiftDisplay, tokenData, Token::type, Token::value.
Referenced by RunMain.
void UpdateRows()
References CALCULATOR_MODE, CHANGE_PASSWORD, LCD_CHAR_S, LCD_N_COL, LcdPrintString, LcdSetCursor, LOGIC_INPUT_ROWS, LOGIC_SHORTCUTS_ROW, LOGIC_STATBAR_ROW, LOGIN_MODE, mode, UpdateShift.
Referenced by DisplayMessage, RefreshDisplay, RunChangePassword, RunLogin, RunMain.
void InitAll()
Initializes all components.
References ClockInit, flashData, FlashDataIsRead, FlashInit, FlashRead, FlashWrite, inputData, isInit, KeypadInit, LcdInit, ParserInit, tokenData.
Referenced by main.
void RunMain()
Runs the main loop.
References CALCULATOR_MODE, CHANGE_PASSWORD, CLEAR_ALL, CLEAR_LAST, ClearAllInput, ClearLastInput, DelayMilli, DISPLAY_NORMAL, END_INPUT, GetSpecialFunction, GO_BACK, isShiftOn, KeypadCreateDefaulteKey, KeypadWaitForKeyInfo, LcdClearDisplay, LOGIN_MODE, mode, KeyInfo::normalDisplayType, OPEN_CHANGE_PASSWORD, RefreshDisplay, RunCalculator, RunChangePassword, RunLogin, RunUserInput, SHIFT_OFF, SHIFT_ON, KeyInfo::shiftDisplayType, UpdateRows, UpdateShift.
Referenced by main.