main.c
LCD_DATA_PORT
LCD_EN_PORT
LCD_EN_PIN
LCD_RS_PORT
LCD_RS_PIN
LCD_CLEAR
LCD_RETURN_HOME
LCD_ENTRY_MODE
LCD_DISPLAY_ON
void Delay1ms(unsigned long milliseconds)
Referenced by InitDisplay, main, SendDisplayNibble.
void SendDisplayNibble(unsigned char nibble, unsigned char mode)
References Delay1ms, LCD_DATA_PORT, LCD_EN_PIN, LCD_EN_PORT, LCD_RS_PIN, LCD_RS_PORT.
void InitDisplay()
References Delay1ms, SendDisplayNibble.
Referenced by main.
void PrintString(char *str)
References SendDisplayNibble.
Referenced by main.
int main()
References Delay1ms, InitDisplay, LCD_CLEAR, LCD_RETURN_HOME, PortAInit, PortBInit, PrintString, SendDisplayNibble.