parser.c
TokenList tokens
Referenced by GetNextToken, ParserInit, ParserInitWith, ParserPushToken, ParserReset, ParserStop, PeekNextToken.
float currentResult
Referenced by ParserCompile, ParserInit, ParserInitWith, ParserReset.
float previousResult
Referenced by ParseNumber, ParserInit, ParserInitWith, ParserReset.
ParserInfo ParseNumber()
Parses only number tokens.
ParserInfo
References ParserInfo::currentResult, DECIMAL, EOL, ParserInfo::error, GetNextToken, MISSING_NUMBER, MULTIPLE_DECIMAL_POINT, NO_ERROR, NUMBER, ParseBracket, PeekNextToken, PREVIOUS_ANSWER, previousResult, ParserInfo::token, Token::type, Token::value.
Referenced by ParseTerm.
ParserInfo ParseTerm()
Parses term tokens.
ParserInfo
References ParserInfo::currentResult, ParserInfo::error, GetNextToken, NO_ERROR, ParseBracket, ParseNumber, PeekNextToken, Token::value.
Referenced by ParseExpression.
ParserInfo ParseBracket()
Parses bracket expression.
ParserInfo
References ParserInfo::error, GetNextToken, MISSING_BRACKET, NO_ERROR, ParseExpression, PeekNextToken, ParserInfo::token, Token::value.
Referenced by ParseExpression, ParseNumber, ParseTerm.
ParserInfo ParseExpression()
Parses arithematic expression.
ParserInfo
References ParserInfo::currentResult, ParserInfo::error, GetNextToken, NO_ERROR, ParseBracket, ParseTerm, PeekNextToken, Token::value.
Referenced by ParseBracket, ParserCompile.
Token PeekNextToken()
Peeks next token.
Token
References tokens.
Referenced by ParseBracket, ParseExpression, ParseNumber, ParserCompile, ParseTerm.
Token GetNextToken()
Eats the next token.
Token
References tokens.
Referenced by ParseBracket, ParseExpression, ParseNumber, ParserCompile, ParseTerm.
DEFINE_LIST_IMPLEMENTATION(Token)
void ParserPushToken(Token token)
Pushes new token to the parser can be used after calling.
ParserInit and ParserInitWith token
References tokens.
Referenced by ParserEndInput, RunCalculator.
void ParserEndInput()
Ends the input.
References EOL, ParserPushToken.
Referenced by RunCalculator.
void ParserPopToken()
Removes last pushed token.
void ParserInit()
Initializes the parser.
References currentResult, previousResult, SCB_CPACR, tokens.
Referenced by InitAll.
void ParserInitWith(Token items[], int length)
Initializes the parser with initial token list.
items token list length length of the tokens
References currentResult, previousResult, tokens.
void ParserStop()
Stops the parser and clears all tokens.
References tokens.
Referenced by ParserReset.
void ParserReset()
Calls.
ParserInit then ParserStop
References currentResult, ParserStop, previousResult, tokens.
Referenced by RunCalculator.
ParserInfo ParserCompile()
Compiles the tokens and returns the result.
ParserInfo
References currentResult, ParserInfo::currentResult, EOL, ParserInfo::error, GetNextToken, NO_ERROR, ParseExpression, PeekNextToken, Token::type.
Referenced by RunCalculator.