playground.c
GPIO_PORTF_DATA_R
GPIO_PORTF_DIR_R
GPIO_PORTF_AFSEL_R
GPIO_PORTF_PUR_R
GPIO_PORTF_DEN_R
GPIO_PORTF_LOCK_R
GPIO_PORTF_CR_R
GPIO_PORTF_AMSEL_R
GPIO_PORTF_PCTL_R
SYSCTL_RCGC2_R
unsigned long SW1
unsigned long SW2
void PortF_Init(void)
References delay, GPIO_PORTF_AFSEL_R, GPIO_PORTF_AMSEL_R, GPIO_PORTF_CR_R, GPIO_PORTF_DEN_R, GPIO_PORTF_DIR_R, GPIO_PORTF_LOCK_R, GPIO_PORTF_PCTL_R, GPIO_PORTF_PUR_R, SYSCTL_RCGC2_R.
void FlashSOS(void)
References delay, GPIO_PORTF_DATA_R.
void delay(unsigned long halfsecs)
Referenced by DelayNano, FlashSOS, PortAInit, PortBInit, PortDInit, PortEInit, PortF_Init, PortFInit, SysTickWait.