ports.h
PORTS_H
GPIO_PORTE_DATA_R
GPIO_PORTE_DIR_R
GPIO_PORTE_AFSEL_R
GPIO_PORTE_PUR_R
GPIO_PORTE_PDR_R
GPIO_PORTE_DEN_R
GPIO_PORTE_LOCK_R
GPIO_PORTE_CR_R
GPIO_PORTE_AMSEL_R
GPIO_PORTE_PCTL_R
GPIO_PORTD_DATA_R
GPIO_PORTD_DIR_R
GPIO_PORTD_AFSEL_R
GPIO_PORTD_PUR_R
GPIO_PORTD_DEN_R
GPIO_PORTD_LOCK_R
GPIO_PORTD_CR_R
GPIO_PORTD_AMSEL_R
GPIO_PORTD_PCTL_R
GPIO_PORTB_DATA_R
GPIO_PORTB_DIR_R
GPIO_PORTB_AFSEL_R
GPIO_PORTB_PUR_R
GPIO_PORTB_DEN_R
GPIO_PORTB_LOCK_R
GPIO_PORTB_CR_R
GPIO_PORTB_AMSEL_R
GPIO_PORTB_PCTL_R
GPIO_PORTA_DATA_R
GPIO_PORTA_DIR_R
GPIO_PORTA_AFSEL_R
GPIO_PORTA_PUR_R
GPIO_PORTA_DEN_R
GPIO_PORTA_LOCK_R
GPIO_PORTA_CR_R
GPIO_PORTA_AMSEL_R
GPIO_PORTA_PCTL_R
GPIO_PORTF_DATA_R
GPIO_PORTF_DIR_R
GPIO_PORTF_AFSEL_R
GPIO_PORTF_PUR_R
GPIO_PORTF_DEN_R
GPIO_PORTF_LOCK_R
GPIO_PORTF_CR_R
GPIO_PORTF_AMSEL_R
GPIO_PORTF_PCTL_R
void PortEInit()
Initiates Port E.
References delay, GPIO_PORTE_CR_R, GPIO_PORTE_DEN_R, GPIO_PORTE_DIR_R, GPIO_PORTE_PDR_R, SYSCTL_RCGC2_R.
Referenced by KeypadInit.
void PortDInit()
Initiates Port D.
References delay, GPIO_PORTD_CR_R, GPIO_PORTD_DEN_R, GPIO_PORTD_DIR_R, SYSCTL_RCGC2_R.
Referenced by KeypadInit.
void PortBInit()
Initiates Port B.
References delay, GPIO_PORTB_DEN_R, GPIO_PORTB_DIR_R, SYSCTL_RCGC2_R.
Referenced by LcdInit.
void PortAInit()
Initiates Port A.
References delay, GPIO_PORTA_DEN_R, GPIO_PORTA_DIR_R, SYSCTL_RCGC2_R.
Referenced by LcdInit.
void PortFInit()
Initializes port F.
References delay, GPIO_PORTF_AFSEL_R, GPIO_PORTF_AMSEL_R, GPIO_PORTF_CR_R, GPIO_PORTF_DEN_R, GPIO_PORTF_DIR_R, GPIO_PORTF_LOCK_R, GPIO_PORTF_PCTL_R, SYSCTL_RCGC2_R.