ports.c
void PortEInit()
Initiates Port E.
References GPIO_PORTE_CR_R, GPIO_PORTE_DEN_R, GPIO_PORTE_DIR_R, GPIO_PORTE_PDR_R, SYSCTL_RCGC2_R.
Referenced by KeypadInit.
void PortDInit()
Initiates Port D.
References GPIO_PORTD_CR_R, GPIO_PORTD_DEN_R, GPIO_PORTD_DIR_R, SYSCTL_RCGC2_R.
Referenced by KeypadInit.
void PortBInit()
Initiates Port B.
References GPIO_PORTB_DEN_R, GPIO_PORTB_DIR_R, SYSCTL_RCGC2_R.
Referenced by LcdInit.
void PortAInit()
Initiates Port A.
References GPIO_PORTA_DEN_R, GPIO_PORTA_DIR_R, SYSCTL_RCGC2_R.
Referenced by LcdInit.
void PortFInit()
Initializes port F.
References GPIO_PORTF_AFSEL_R, GPIO_PORTF_AMSEL_R, GPIO_PORTF_CR_R, GPIO_PORTF_DEN_R, GPIO_PORTF_DIR_R, GPIO_PORTF_LOCK_R, GPIO_PORTF_PCTL_R, SYSCTL_RCGC2_R.