unit-test.c
void AfterEach()
References DelayMilli, LcdClearDisplay.
void TestLcdClear()
References DelayMilli, LcdClearDisplay, LcdPrintChar.
void TestLcdCursor()
References LcdPrintString, LcdSetCursor.
void TestLcdMultiLine()
References DelayMilli, LcdClearDisplay, LcdPrintString.
Referenced by TestLcdAll.
void TestLcdAll()
References TestLcdMultiLine.
void TestKeypadLcd()
References DelayMilli, KeyInfo::key, KeypadWaitForInput, LcdClearDisplay, LcdPrintChar, LcdPrintString.
Referenced by RunAll.
void RunAll()
Runs all unit test functions.
References TestKeypadLcd.
Referenced by main.